### PR TITLE
Removed deprecated erlang 19 warnings

### PR DESCRIPTION
**Pull request by shamis**
changed random module to rand and erlang:now() to os:timestamp()

### CODE REVIEW

**Comment by stoch** [comment]
@shamis @c-bik We should not use os:timestamp anywhere in our code. Where is this used now?

**Comment by shamis** [comment]
@stoch This is used [here](https://github.com/K2InformaticsGmbH/erloci/pull/48/files#diff-05b1fa79d3e0a67b990a3f82311fdeb4L39). It is only used in the test SUITE.

**Comment by stoch** [comment]
If unique timestamps are not required, os:timestamp are OK for debugging purposes. If imem is a dependency, imem_meta:time() is still preferred to represent time because it then is comparable to other logs of the system.

**Comment by c-bik** [comment]
@stoch imem isn't a dependency of erloci or erlocipool projects.
For erlang applications/projects (which do not have imem deps), we have to rely on erlang native time APIs

**Comment by stoch** [comment]
@c-bik Agreed, but we must pick the same time concept everywhere.

This means in our case: adapted system time (default VM start parameters);
:
timestamp() -> 
    SystemTime = erlang:system_time(1000000),                 % or less resolution
    {SystemTime div 1000000, SystemTime rem 1000000}.  % or whatever format you need

**Pull request merged**
