### PR TITLE
Updated MacOS Makefile to use libnnz12

### PR DESCRIPTION
**Pull request by whitepaperclip**
This is being shipped now in the latest version of Instant Client for MacOS.

### CODE REVIEW

**Comment by acautin** [comment]
@c-bik this seems to be correct as @seanhinde had to fix it to compile using the latest oci client version.

**Comment by c-bik** [comment]
Thanks for your contribution @whitepaperclip 👍

**Comment by seanhinde** [comment]
We should maybe consider a version check for future releases, or at least document this needs to change based on installed version of the Oracle libs

**Comment by c-bik** [comment]
> We should maybe consider a version check for future releases, or at least document this needs to change based on installed version of the Oracle libs

@seanhinde do you have an idea how can we do that (installed rpm version check commands in makefile?)

**Comment by seanhinde** [comment]
could run instantclient_12_2/sqlplus -V and parse out the numbers from there

**Comment by seanhinde** [comment]
More specifically:
`INSTANT_CLIENT_LIB_PATH/sqlpus -V`

**Comment by whitepaperclip** [comment]
Hmm. I don't know about you guys, but I don't have sqlplus installed. Would it be too ugly to pick whatever version of the libs they have installed, just based on the file name?

**Comment by c-bik** [comment]
@whitepaperclip alternatively...
```sh
rpm -qa | grep oracle-instantclient
oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64
oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64
```
.. then `awk`, `sed` etc...

**Comment by seanhinde** [comment]
Macs won't have rpm so that won't work generically.

I must have installed something more than the basic libs package to end up with sqlplus. 
@whitepaperclip do you have anything executable in your instantclient directory?

**Comment by c-bik** [comment]
True, my bad!

**Comment by seanhinde** [comment]
how about grepping out OCI_MAJOR_VERSION from oci.h ?

**Comment by whitepaperclip** [comment]
For what it's worth, none of the other libraries I have in my directory have version numbers included, other than `libnnz12`. So this would work, presumably:

```
$ ls oracle/macos/lib/libnnz* | grep -oE '[0-9]+'
12
```

Which could then be used to specify the `libnnz` version.

**Comment by whitepaperclip** [comment]
(Perhaps a bit safer: `ls oracle/macos/lib/libnnz??\.dylib | grep -oE '[0-9]+'`)

**Comment by cjbj** [comment]
I haven't dug into your build process, but in general we (Oracle) [document that on macOS](http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst) the Oracle libs should be in ~/lib or /usr/local/lib. Your link line could then just use libclntsh, possibly with rpath.

**Pull request merged**
